### ISSUE TITLE
Futex not found due to wrong UID in name

### ISSUE THREAD

**Issue by kennypm** [oleg68/jackfreqd#6]
Using jackfreqd 0.2.2-1, JACK 1.9.19, Pure Data 0.52.0-test4

`sudo jackfreqd -wPvvv`
>/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies: No such file or directory
/sys/devices/system/cpu/cpu1/cpufreq/scaling_available_frequencies: No such file or directory
/sys/devices/system/cpu/cpu2/cpufreq/scaling_available_frequencies: No such file or directory
/sys/devices/system/cpu/cpu3/cpufreq/scaling_available_frequencies: No such file or directory
/sys/devices/system/cpu/cpu4/cpufreq/scaling_available_frequencies: No such file or directory
/sys/devices/system/cpu/cpu5/cpufreq/scaling_available_frequencies: No such file or directory
/sys/devices/system/cpu/cpu6/cpufreq/scaling_available_frequencies: No such file or directory
/sys/devices/system/cpu/cpu7/cpufreq/scaling_available_frequencies: No such file or directory
Found 8 scalable units:  -- 1 'CPU' per scalable unit
  cpu0: 800Mhz - 3400Mhz (27 steps)
  cpu1: 800Mhz - 3400Mhz (27 steps)
  cpu2: 800Mhz - 3400Mhz (27 steps)
  cpu3: 800Mhz - 3400Mhz (27 steps)
  cpu4: 800Mhz - 3400Mhz (27 steps)
  cpu5: 800Mhz - 3400Mhz (27 steps)
  cpu6: 800Mhz - 3400Mhz (27 steps)
  cpu7: 800Mhz - 3400Mhz (27 steps)
[ . . . ]
Found jackd running; pid:9300 'jackd' u:1000 g:1000
jack: uid:1000 gid:1000
Connected to the jack server
connected to JACKd
[ . . . ]
Connect: can't connect named futex name = jack_sem.0_default_pure_data err = No such file or directory
[ . . . ]
Disconnected from the jack server
Statistics:
  190 speed changes in 21 seconds
JACKfreqd Daemon Exiting.

Everything seems fine until I turn on DSP in Pure Data and then I get the error beginning with `Connect:`, although the DSP load shown with more `-v` switches does increase. There is a file at `/dev/shm/jack_sem.1000_default_pure_data` so it seems like jackfreqd is getting confused about the uid it needs to be using in the futex name.

**Comment by oleg68** [comment]
> Connect: can't connect named futex name = jack_sem.0_default_pure_data err = No such file or directory

Hm. I need to look at the jack client sourcecode: how does it obtain the user id.

The pipewire jack client uses XDG_RUNTIME_DIR for this purpose.

**Comment by kennypm** [comment]
Yes, I ended up switching to PipeWire for other reasons and never ended up looking into this. I'm happy to work out a fix, for now just leaving [this post](https://linuxmusicians.com/viewtopic.php?p=117857#p117857) here as a record of at least one other person having this issue.

**Comment by oleg68** [comment]
I saw the source code. Jackfreqd calls setresuid, and a jack client calls geteuid. According to https://man7.org/linux/man-pages/man2/setresuid.2.html setresuid should set the value that geteuid returns. But it goes wrong on you system.

I can not reproduce it, If you doesn't more need a solution, may I close this issue?

**Comment by kennypm** [comment]
Sure, still a mystery to me but I found a workaround so I'm happy.

**Comment by kennypm** [comment]
Sure, still a mystery to me after having another look but I found a workaround so I'm happy.
